### ISSUE TITLE
Support for multi-architecture repos

### ISSUE THREAD

**Issue by wieshka** [binxio/cfn-container-image-provider#1]
Thanks for quick lambda based solution which allows me to remove much slower solution built around CodePipelines.

Wonder are there any plans to introduce multi-architecture support as ECR supports multi-arch repos.

**Comment by mvanholsteijn** [comment]
Hi @wieshka, I added Platform support to the provider. By default it will still pull linux/amd64, but you may specify 'all' or a specific platform through the `Platform` property.

release in 0.4.0
